// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjz33r1P2oRhciZxy5AiDxz9KaTCTxEhk',
    appId: '1:848249088068:web:b8cd7406922d34f3e73411',
    messagingSenderId: '848249088068',
    projectId: 'messease-97d1b',
    authDomain: 'messease-97d1b.firebaseapp.com',
    storageBucket: 'messease-97d1b.firebasestorage.app',
    measurementId: 'G-5NG5BH1N06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9iCcYOT2C4dLOpP-EeSZtDh25eYtQ5GQ',
    appId: '1:848249088068:android:a1f28891a62a4dbde73411',
    messagingSenderId: '848249088068',
    projectId: 'messease-97d1b',
    storageBucket: 'messease-97d1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKET25vnXp23zNmAP97dx7KPrX6efH5h4',
    appId: '1:848249088068:ios:c038ffda0ed18580e73411',
    messagingSenderId: '848249088068',
    projectId: 'messease-97d1b',
    storageBucket: 'messease-97d1b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKET25vnXp23zNmAP97dx7KPrX6efH5h4',
    appId: '1:848249088068:ios:c038ffda0ed18580e73411',
    messagingSenderId: '848249088068',
    projectId: 'messease-97d1b',
    storageBucket: 'messease-97d1b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjz33r1P2oRhciZxy5AiDxz9KaTCTxEhk',
    appId: '1:848249088068:web:e5088046b733c0a6e73411',
    messagingSenderId: '848249088068',
    projectId: 'messease-97d1b',
    authDomain: 'messease-97d1b.firebaseapp.com',
    storageBucket: 'messease-97d1b.firebasestorage.app',
    measurementId: 'G-CX6880B3P3',
  );
}
